spring:
  redis:
    host: 192.168.2.128
    port: 6379
  #  password: BlockchainTest@redis0312
    jedis:
      pool:
        max-active: 200
        max-wait: -1
        max-idle: 10
        min-idle: 0

management:
  health:
    redis:
      enabled: false
